#
# Application URLS
#

development:
  cas_url: "https://aztec.ncgr.org:7777"
  cas_validate: "https://aztec.ncgr.org:7777/proxyValidate"
  root_url: "http://aztec.ncgr.org:7650/"

production:
  cas_url: "https://cas.comparative-legumes.org" 
  cas_validate: "https://velarde.ncgr.org:8055/proxyValidate"
  root_url: "http://comparative-legumes.org/"

test:
  cas_url: "https://aztec.ncgr.org:7777"
  cas_validate: "https://aztec.ncgr.org:7777/proxyValidate"
  root_url: "http://aztec.ncgr.org:7650/"

